SET(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)
BA_PACKAGE_LIBRARY(fleet-protocol-interface v${FLEET_PROTOCOL_INTERFACE_VERSION} PLATFORM_STRING_MODE any_machine NO_DEBUG ON)

IF (BRINGAUTO_TESTS)
    BA_PACKAGE_LIBRARY(gtest    v1.12.1)
ENDIF ()